CREATE TABLE IF NOT EXISTS patients (
  id SERIAL PRIMARY KEY,
  case_number TEXT NOT NULL,
  sequence_number INTEGER NOT NULL,
  patient_name TEXT NOT NULL,
  contact_info TEXT,
  admission_date TEXT,
  age INTEGER NOT NULL,
  hypertension INTEGER NOT NULL DEFAULT 0,
  diabetes INTEGER NOT NULL DEFAULT 0,
  cardiovascular INTEGER NOT NULL DEFAULT 0,
  other_comorbidities INTEGER NOT NULL DEFAULT 0,
  pregnancy_history TEXT,
  hpv_status TEXT,
  pre_treatment_tumor_size_category INTEGER,
  pre_treatment_tumor_size REAL,
  post_treatment_tumor_size REAL,
  tumor_size_change REAL,
  tumor_size_change_pct REAL,
  pre_scc_ag REAL,
  post_scc_ag REAL,
  pre_ca125 REAL,
  post_ca125 REAL,
  pre_cea REAL,
  post_cea REAL,
  pre_ca199 REAL,
  post_ca199 REAL,
  platelet_count REAL,
  lymphocyte_count REAL,
  neutrophil_count REAL,
  monocyte_count REAL,
  serum_albumin REAL,
  plr REAL,
  lmr REAL,
  pni REAL,
  sii REAL,
  piv REAL,
  pre_hemoglobin REAL,
  figo_stage_2009 TEXT,
  figo_stage_2018 TEXT,
  pathology_type TEXT,
  differentiation TEXT,
  parametrial_invasion TEXT,
  vaginal_invasion TEXT,
  pelvic_lymph_node_metastasis INTEGER NOT NULL DEFAULT 0,
  inguinal_lymph_node_metastasis INTEGER NOT NULL DEFAULT 0,
  common_iliac_lymph_node_metastasis INTEGER NOT NULL DEFAULT 0,
  para_aortic_lymph_node_metastasis INTEGER NOT NULL DEFAULT 0,
  supraclavicular_lymph_node_metastasis INTEGER NOT NULL DEFAULT 0,
  radiation_dose TEXT,
  brachytherapy TEXT,
  brachytherapy_three_tube TEXT,
  brachytherapy_implant TEXT,
  brachytherapy_dose TEXT,
  eqd2_point_a REAL,
  concurrent_chemo_cycles INTEGER,
  hyperthermia TEXT,
  immunotherapy TEXT,
  total_treatment_days INTEGER,
  post_lymph_node_status TEXT,
  os TEXT,
  pfs TEXT,
  treatment_outcome TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS imaging_records (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  imaging_dept_id TEXT,
  imaging_year INTEGER,
  source_file TEXT,
  modality TEXT NOT NULL,
  body_part TEXT NOT NULL,
  study_date TIMESTAMPTZ NOT NULL,
  description TEXT,
  findings TEXT,
  image_url TEXT,
  mask_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS radiomics_features (
  id SERIAL PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  feature_class TEXT NOT NULL,
  feature_name TEXT NOT NULL,
  feature_value REAL NOT NULL,
  imaging_id INTEGER REFERENCES imaging_records(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
