import { pgTable, text, serial, integer, real, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const patientsTable = pgTable("patients", {
  id: serial("id").primaryKey(),
  caseNumber: text("case_number").notNull(),
  sequenceNumber: integer("sequence_number").notNull(),
  patientName: text("patient_name").notNull(),
  contactInfo: text("contact_info"),
  admissionDate: text("admission_date"),
  age: integer("age").notNull(),
  hypertension: integer("hypertension").notNull().default(0),
  diabetes: integer("diabetes").notNull().default(0),
  cardiovascular: integer("cardiovascular").notNull().default(0),
  otherComorbidities: integer("other_comorbidities").notNull().default(0),
  pregnancyHistory: text("pregnancy_history"),
  hpvStatus: text("hpv_status"),
  preTreatmentTumorSizeCategory: integer("pre_treatment_tumor_size_category"),
  preTreatmentTumorSize: real("pre_treatment_tumor_size"),
  postTreatmentTumorSize: real("post_treatment_tumor_size"),
  tumorSizeChange: real("tumor_size_change"),
  tumorSizeChangePct: real("tumor_size_change_pct"),
  preSccAg: real("pre_scc_ag"),
  postSccAg: real("post_scc_ag"),
  preCa125: real("pre_ca125"),
  postCa125: real("post_ca125"),
  preCea: real("pre_cea"),
  postCea: real("post_cea"),
  preCa199: real("pre_ca199"),
  postCa199: real("post_ca199"),
  plateletCount: real("platelet_count"),
  lymphocyteCount: real("lymphocyte_count"),
  neutrophilCount: real("neutrophil_count"),
  monocyteCount: real("monocyte_count"),
  serumAlbumin: real("serum_albumin"),
  plr: real("plr"),
  lmr: real("lmr"),
  pni: real("pni"),
  sii: real("sii"),
  piv: real("piv"),
  preHemoglobin: real("pre_hemoglobin"),
  figoStage2009: text("figo_stage_2009"),
  figoStage2018: text("figo_stage_2018"),
  pathologyType: text("pathology_type"),
  differentiation: text("differentiation"),
  parametrialInvasion: text("parametrial_invasion"),
  vaginalInvasion: text("vaginal_invasion"),
  pelvicLymphNodeMetastasis: integer("pelvic_lymph_node_metastasis").notNull().default(0),
  inguinalLymphNodeMetastasis: integer("inguinal_lymph_node_metastasis").notNull().default(0),
  commonIliacLymphNodeMetastasis: integer("common_iliac_lymph_node_metastasis").notNull().default(0),
  paraAorticLymphNodeMetastasis: integer("para_aortic_lymph_node_metastasis").notNull().default(0),
  supraclavicularLymphNodeMetastasis: integer("supraclavicular_lymph_node_metastasis").notNull().default(0),
  radiationDose: text("radiation_dose"),
  brachytherapy: text("brachytherapy"),
  brachytherapyThreeTube: text("brachytherapy_three_tube"),
  brachytherapyImplant: text("brachytherapy_implant"),
  brachytherapyDose: text("brachytherapy_dose"),
  eqd2PointA: real("eqd2_point_a"),
  concurrentChemoCycles: integer("concurrent_chemo_cycles"),
  hyperthermia: text("hyperthermia"),
  immunotherapy: text("immunotherapy"),
  totalTreatmentDays: integer("total_treatment_days"),
  postLymphNodeStatus: text("post_lymph_node_status"),
  os: text("os"),
  pfs: text("pfs"),
  treatmentOutcome: text("treatment_outcome"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertPatientSchema = createInsertSchema(patientsTable).omit({ id: true, createdAt: true });
export type InsertPatient = z.infer<typeof insertPatientSchema>;
export type Patient = typeof patientsTable.$inferSelect;
